# Generated by Django 4.1.4 on 2023-02-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='font_awesome_icon',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
